### ISSUE TITLE
Unstable GUI

### ISSUE THREAD

**Issue by DiogenesNakamoto** [monero-project/monero-core#69]
I followed the steps for installing the GUI as outlined here, and everything went fine. I was able to create a new wallet, everything looked fine (albeit poor scaling on my 4k display). When I opened the wallet, the GUI was unstable with flickering distortion across all elements as seen here: http://imgur.com/a/6k6O3

I'm running a clean install of Ubuntu 16.04.1 and haven't had any issues with any other applications.

**Comment by Jaqueeee** [comment]
Thank you for testing!
We haven't seen this behavior before.  Could you please try opening the GUI again when the daemon is fully synced? I'm not sure if it's related, but just to ensure it isn't.

**Comment by medusadigital** [comment]
@DiogenesNakamoto probably the resolution. can you try change the resolution down and reopen monero-core?

**Comment by DiogenesNakamoto** [comment]
I changed the resolution to 1080p and the scaling back to 1.0. As you can see, the password entry field looks normal, but the app is unchanged.

http://imgur.com/a/WJyZI

**Comment by DiogenesNakamoto** [comment]
I am running two monitors on a Nvidia 980 Ti with Nvidia driver 370.28

**Comment by DiogenesNakamoto** [comment]
deamon is synced. No change. In this image you can see that 2 elements are displayed correctly, the connection status indicator and the seed recovery box.

http://imgur.com/a/GadMe

**Comment by medusadigital** [comment]
im experiencing the same issue on win 7 x64 today. 2560x1440. had no isses with ubuntu on 1440p.

very strange
![brokenfont](https://cloud.githubusercontent.com/assets/17108301/19441642/a5b136c4-9486-11e6-9fc7-7ce32e171a90.png)

**Comment by Jaqueeee** [comment]
Could you try to add this line to the bottom of monero-core.pro, rebuild and see if it makes any difference? @DiogenesNakamoto @medusadigital 

`QT_AUTO_SCREEN_SCALE_FACTOR = 1`

**Comment by DiogenesNakamoto** [comment]
Added. No change.

**Comment by Jaqueeee** [comment]
ok. thanks anyway

**Comment by kragol** [comment]
I have the same problem on Arch Linux (up to date) using the KDE Plasma desktop. GPU is also Nvidia (GTX 970) using the proprietary driver 370.28.

**Comment by medusadigital** [comment]
@kragol what resolution do you got?

**Comment by kragol** [comment]
@medusadigital my monitor's native resolution 1920x1080.

**Comment by dEBRUYNE-1** [comment]
@DiogenesNakamoto & @kragol, could you both try the following instructions:

1. Download the following file:

64-bit:

https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-mesa-11.2.0-1-any.pkg.tar.xz/download

32-bit:

https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/mingw-w64-i686-mesa-11.2.0-1-any.pkg.tar.xz/download


2. Extract the file. 

3. Place `opengl32.dll` in the same folder as `monero-core` is located. 

This fixed the rendering issue for @medusadigital on Windows 64 bit.

**Comment by medusadigital** [comment]
Issue is solved on windows, but how does the Linux fix look like?

**Comment by kragol** [comment]
@medusadigital, the closest I could get to your fix on Linux was to replace the proprietary nvidia driver with the open source "nouveau" driver. It did not fix the problem.

**Comment by dEBRUYNE-1** [comment]
@kragol, could you try the following:

>So, try this if your are on Mac or Linux like OS from terminal:

>export QMLSCENE_DEVICE=softwarecontext
>./yourAppExecutable

It's from [here](http://lists.qt-project.org/pipermail/interest/2015-October/019486.html).

**Comment by kragol** [comment]
I guess I answered a bit too quickly...

After updating my system and recompiling everything just now, the problem seems to be gone. I'm not sure exactly what was the culprit. All I know is that I could not run monero-core after the system update because of a change of libboost version (1.61 -> 1.62). Also, I am back to using the nvidia proprietary driver.

**Comment by maitscha** [comment]
`boost` 1.62 seems to be incompatible with the current `master` branch. I had the same issue under MacOS, see for example #57 and #101.

**Comment by kragol** [comment]
I can definitely build with `boost` 1.62 on Arch Linux (everything up to date). I haven't had time to check that all programs in the monero suite work properly but at least they build without errors.

**Comment by DiogenesNakamoto** [comment]
Issue is resolved on my system. I didn't update the system or make any changes to drivers. I simply rebuilt the app and it is displaying properly.

**Comment by medusadigital** [comment]
Great. can finnaly be closed. good job everyone

**Comment by dternyak** [comment]
@DiogenesNakamoto Can you close this issue?

**Comment by fluffypony** [comment]
Closing as fixed
